apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tct-cluster
  region: us-west-1
  # tags:
  #   karpenter.sh/discovery: tct-cluster
iam:
  withOIDC: true

managedNodeGroups:
  - name: tct-node-group
    amiFamily: AmazonLinux2023
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 5
    spot: true


addons:
- name: eks-pod-identity-agent


